const {
  AUTH_EMAIL_VERIFICATION,
  AUTH_EMAIL_CONFIRMATION,
  AUTH_PHONE_VERIFICATION,
  AUTH_PHONE_CONFIRMATION
} = require('../../../modules/auth/endPoints');

const {
  BRANCH_ADD_BRANCH,
  BRANCH_UPDATE_BRANCH,
  BRANCH_ACTIVATE_BRANCH,
  BRANCH_BUSINESS_BRANCH,
  BRANCH_BUSINESS_BRANCHES
} = require('../../../modules/branch/endPoints');
const {
  PRODUCT_BUSINESS_ACTIVATE_PRODUCT,
  PRODUCT_BUSINESS_ADD_PRODUCT,
  PRODUCT_BUSINESS_UPDATE_PRODUCT,
  PRODUCT_GET_GETPRODUCTS,
  PRODUCT_GET_GETPRODUCT
} = require('../../../modules/product/endPoints');

const {
  CATEGORY_GET_CATEGORIES
} = require('../../../modules/category/endPoints');

module.exports = [
  AUTH_EMAIL_VERIFICATION,
  AUTH_EMAIL_CONFIRMATION,
  AUTH_PHONE_VERIFICATION,
  AUTH_PHONE_CONFIRMATION,
  BRANCH_ADD_BRANCH,
  BRANCH_UPDATE_BRANCH,
  BRANCH_ACTIVATE_BRANCH,
  BRANCH_BUSINESS_BRANCH,
  BRANCH_BUSINESS_BRANCHES,
  PRODUCT_BUSINESS_ACTIVATE_PRODUCT,
  PRODUCT_BUSINESS_ADD_PRODUCT,
  PRODUCT_BUSINESS_UPDATE_PRODUCT,
  CATEGORY_GET_CATEGORIES,
  PRODUCT_GET_GETPRODUCTS,
  PRODUCT_GET_GETPRODUCT
];
